variable "project_name" {
  type        = string
  description = "Short resource prefix."
  default     = "eastmed"
}

variable "environment" {
  type        = string
  description = "Deployment environment."
  default     = "production"
}

variable "aws_region" {
  type        = string
  description = "AWS region; use an EU region unless counsel approves another location."
  default     = "eu-central-1"
}

variable "vpc_cidr" {
  type        = string
  description = "VPC CIDR."
  default     = "10.42.0.0/16"
}

variable "app_domain" {
  type        = string
  description = "Production desk and portal host, without scheme."
}

variable "api_domain" {
  type        = string
  description = "Production API host, without scheme."
}

variable "route53_zone_id" {
  type        = string
  description = "Existing public Route53 hosted-zone ID for both hosts."
}

variable "alarm_email" {
  type        = string
  description = "Human-owned operational mailbox. The SNS subscription must be confirmed."
}

variable "clerk_publishable_key" {
  type        = string
  description = "Clerk production publishable key; embedded into the web image at build time."
}

variable "clerk_issuer" {
  type        = string
  description = "Clerk production Frontend API issuer URL."

  validation {
    condition     = startswith(var.clerk_issuer, "https://")
    error_message = "Clerk issuer must use HTTPS."
  }
}

variable "claim_extraction_system_fingerprint" {
  type        = string
  description = "Approved SHA-256 fingerprint for the exact shadow extraction system manifest."

  validation {
    condition     = can(regex("^[0-9a-f]{64}$", var.claim_extraction_system_fingerprint))
    error_message = "The extraction fingerprint must be 64 lowercase hexadecimal characters."
  }
}

variable "allowed_fetch_hosts" {
  type        = string
  description = "Comma-separated host allowlist generated by scripts/render_source_allowlist.py."
}

variable "enable_postmark" {
  type        = bool
  description = "Inject Postmark delivery credentials; outbound remains globally disabled."
  default     = false
}

variable "postmark_from_email" {
  type        = string
  description = "Verified Postmark sender used when enable_postmark is true."
  default     = ""
}

variable "postmark_message_stream" {
  type        = string
  description = "Accepted Postmark transactional stream."
  default     = "alerts"
}

variable "enable_telegram" {
  type        = bool
  description = "Inject the customer Telegram bot token."
  default     = false
}

variable "enable_whatsapp" {
  type        = bool
  description = "Inject accepted 360dialog/WhatsApp credentials and webhook authentication."
  default     = false
}

variable "whatsapp_webhook_username" {
  type        = string
  description = "Non-secret username for WhatsApp webhook Basic authentication."
  default     = ""
}

variable "enable_sentry" {
  type        = bool
  description = "Inject a reviewed Sentry DSN; tracing remains disabled."
  default     = false
}

variable "image_tag" {
  type        = string
  description = "Immutable API/web image tag. Never deploy latest."
  default     = "bootstrap"
}

variable "activate_services" {
  type        = bool
  description = "Keep false until migration, role bootstrap, identity and restore acceptance pass."
  default     = false
}

variable "database_instance_class" {
  type    = string
  default = "db.t4g.medium"
}

variable "redis_node_type" {
  type    = string
  default = "cache.t4g.small"
}

variable "deletion_protection" {
  type    = bool
  default = true
}
