"""Private daily fleet reconciliation (blueprint work order 1).

This namespace holds the format-neutral contracts for MariTime's private analytical
path: the versioned ``fleet_reconciliation_v1`` data contract and the expected-work
ledger. It is deliberately separate from the existing human-operated event desk so
new autonomous behavior cannot publish into the public event stream (blueprint 29,
phase 1).

Nothing here reaches a database, a queue or a model. These are the definitions that
later work orders (schema/migrations, deterministic calculator, durable runtime)
build on. Code here is a proposed specification made executable and testable, not a
deployed service.
"""

from __future__ import annotations

from eastmed_shared.reconciliation.calculator import (
    CALCULATOR_VERSION,
    CalcRefusal,
    CalcRefusalReason,
    FleetSummaryResult,
    FuelVarianceResult,
    Interval,
    QuantityInput,
    VesselGradeResult,
    fleet_summary,
    fuel_variance,
    planned_actual_delta,
    report_period_reconcile,
)
from eastmed_shared.reconciliation.canary import (
    REQUIRED_PREREQS,
    ROLLBACK_CANARY_RUNBOOK,
    CanaryAdmission,
    CanaryManifest,
    CanaryPrereq,
    ConfigPackage,
    RollbackDecision,
    action_permitted,
    canary_admission,
    canary_scope_ok,
    check_canary_regression,
)
from eastmed_shared.reconciliation.contract import (
    CONTRACT_VERSION,
    AuthorityRole,
    FuelGrade,
    NormalizedObservation,
    NormalizedRecord,
    QuantityUnit,
    RecordKind,
    Rejection,
    RejectionReason,
    ValueOrigin,
    validate_record,
)
from eastmed_shared.reconciliation.explanation import (
    ExplanationContext,
    ExplanationModel,
    ExplanationOutcome,
    ExplanationSentence,
    ExplanationStatus,
    ModelError,
    ModelFailureKind,
    ModelRequest,
    ModelResponse,
    explain_case,
)
from eastmed_shared.reconciliation.ledger import (
    AutomationStatus,
    BusinessStatus,
    CompletionSummary,
    ExpectedJob,
    JobObservation,
    JobOutcome,
    summarize_ledger,
)
from eastmed_shared.reconciliation.pilot import (
    ACCEPTANCE_CAVEAT,
    DecisionRecord,
    GateStatus,
    GateTier,
    PilotAcceptance,
    PilotGate,
    PilotObservations,
    PilotReadiness,
    evaluate_pilot,
)
from eastmed_shared.reconciliation.policy import (
    ActionRequest,
    DenyReason,
    GrantView,
    PolicyDecision,
    PrincipalView,
    canonical_payload_hash,
    evaluate_policy,
)
from eastmed_shared.reconciliation.read_model import (
    CUSTOMER_ACTIONS,
    READ_MODEL_VERSION,
    EmptyState,
    EvidenceStatus,
    FleetTotal,
    FleetTotalGroup,
    MaterialValue,
    PresentationStatus,
    VesselResultView,
    build_fleet_total,
    daily_report_empty_state,
    is_completed,
    label_variances,
    next_machine_step,
    presentation_status,
)
from eastmed_shared.reconciliation.recovery import (
    RecoveryAction,
    RecoveryDecision,
    TaskFailureKind,
    select_recovery,
)
from eastmed_shared.reconciliation.release import (
    ReleaseCheck,
    ReleaseMetrics,
    ReleaseThresholds,
    ReleaseVerdict,
    SealedManifest,
    clopper_pearson_lower,
    evaluate_release,
    evaluate_sealed,
    percentile,
)
from eastmed_shared.reconciliation.runbooks import (
    RUNBOOK_REGISTRY,
    RunbookAdmission,
    RunbookApiCall,
    RunbookPrecondition,
    RunbookRejection,
    RunbookSpec,
    authorize_runbook,
)
from eastmed_shared.reconciliation.telemetry import (
    MetricSet,
    TelemetrySnapshot,
    TraceContext,
    build_metrics,
)
from eastmed_shared.reconciliation.verifier import (
    CaseCompletionStatus,
    EvidenceFact,
    VerificationStatus,
    VerificationVerdict,
    VerifyReason,
    finalize_case_status,
    verify_case_result,
)

__all__ = [
    "ACCEPTANCE_CAVEAT",
    "CALCULATOR_VERSION",
    "CONTRACT_VERSION",
    "CUSTOMER_ACTIONS",
    "DecisionRecord",
    "GateStatus",
    "GateTier",
    "PilotAcceptance",
    "PilotGate",
    "PilotObservations",
    "PilotReadiness",
    "evaluate_pilot",
    "READ_MODEL_VERSION",
    "REQUIRED_PREREQS",
    "ROLLBACK_CANARY_RUNBOOK",
    "RUNBOOK_REGISTRY",
    "AuthorityRole",
    "CanaryAdmission",
    "CanaryManifest",
    "CanaryPrereq",
    "ConfigPackage",
    "MetricSet",
    "ReleaseCheck",
    "ReleaseMetrics",
    "ReleaseThresholds",
    "ReleaseVerdict",
    "RollbackDecision",
    "RunbookAdmission",
    "RunbookApiCall",
    "RunbookPrecondition",
    "RunbookRejection",
    "RunbookSpec",
    "SealedManifest",
    "TelemetrySnapshot",
    "TraceContext",
    "action_permitted",
    "authorize_runbook",
    "build_metrics",
    "canary_admission",
    "canary_scope_ok",
    "check_canary_regression",
    "clopper_pearson_lower",
    "evaluate_release",
    "evaluate_sealed",
    "percentile",
    "AutomationStatus",
    "BusinessStatus",
    "ActionRequest",
    "EmptyState",
    "EvidenceStatus",
    "FleetTotal",
    "FleetTotalGroup",
    "MaterialValue",
    "PresentationStatus",
    "VesselResultView",
    "build_fleet_total",
    "daily_report_empty_state",
    "is_completed",
    "label_variances",
    "next_machine_step",
    "presentation_status",
    "CalcRefusal",
    "CalcRefusalReason",
    "CaseCompletionStatus",
    "CompletionSummary",
    "DenyReason",
    "GrantView",
    "PolicyDecision",
    "PrincipalView",
    "canonical_payload_hash",
    "evaluate_policy",
    "EvidenceFact",
    "ExpectedJob",
    "ExplanationContext",
    "ExplanationModel",
    "ExplanationOutcome",
    "ExplanationSentence",
    "ExplanationStatus",
    "FleetSummaryResult",
    "FuelGrade",
    "FuelVarianceResult",
    "Interval",
    "JobObservation",
    "JobOutcome",
    "ModelError",
    "ModelFailureKind",
    "ModelRequest",
    "ModelResponse",
    "NormalizedObservation",
    "NormalizedRecord",
    "QuantityInput",
    "QuantityUnit",
    "RecordKind",
    "RecoveryAction",
    "RecoveryDecision",
    "Rejection",
    "RejectionReason",
    "TaskFailureKind",
    "ValueOrigin",
    "VerificationStatus",
    "VerificationVerdict",
    "VerifyReason",
    "VesselGradeResult",
    "explain_case",
    "finalize_case_status",
    "fleet_summary",
    "fuel_variance",
    "planned_actual_delta",
    "report_period_reconcile",
    "select_recovery",
    "summarize_ledger",
    "validate_record",
    "verify_case_result",
]
